<<<<<<< HEAD
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
=======
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import { Providers } from './providers'
>>>>>>> bb251b4e0fa4926329b4db71526291bbfc10a12e

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
<<<<<<< HEAD
  // biome-ignore lint/correctness/noUndeclaredVariables: <explanation>
  children: React.ReactNode;
=======
  children: React.ReactNode
>>>>>>> bb251b4e0fa4926329b4db71526291bbfc10a12e
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
