name: Migration

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'supabase/migrations/**' # migrationsディレクトリ配下に変更があったときのみ起動
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}

      - name: Deploy Migrations
        run: supabase migration up --linked
